name = "cfws-miniflare"
account_id = ""
type = "javascript"
workers_dev = true
compatibility_date = "2021-12-17"

[site]
bucket = "./public"
entry-point = "./src"

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./worker.mjs"
dir = "./dist"
